web:
  image: 2aff7875b0b9
  volumes:
    - "$PWD/app:/app"
  ports:
    - "127.0.0.1:80:80"
  links:
    - db
db:
  image: mysql
  volumes:
    - ./mysql:/etc/mysql/conf.d
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lamp
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
  ports:
    - "127.0.0.1:3306:3306"
